### ISSUE TITLE
Use generated value

### ISSUE THREAD

**Issue by bartekev** [zeronounours/lovelace-energy-entity-row#8]
Hi,
First of all! What a fatastic solution to what I was looking for! 👍 
I do have a question though - I would like to use the generated value in a seperate entity or in a different card !

Let me explain, I'm looking for an overview for a specific date that uses the Power for the specific appliance (I have 10s of appliances) to display the graph of the day with next to it the energy used in that specific day!

So if it's possible to display the value in a, let's say for example, bubble card that would solve everything!
In case this is not possible, I would make a helper to store the generated value in and use this helper for furthr visualisation.

Is this possible to integrate please?

**Comment by zeronounours** [comment]
Hi, actually, this is not possible to use the displayed values in another card or entity.

It won't ever be possible to use it within another entity as the displayed value is only computed on the frontend part. However, I'm thinking for a while to "hack" the retrieval of state to be able to use energy values in any card, something like (of course not working currently):
```yaml
- type: custom:energy-entity-wrapper
  entities:
    - sensor.my_energy_sensor
    - entity: sensor.another_sensor
      wrapped_name: sensor.another_sensor_over_date
  cards:
    - type: entity
      entity: sensor.my_energy_sensor
    - type: glance
      entities:
        - sensor.another_sensor   # would be the current state of the sensor
        - sensor.another_sensor_over_date  # would be the value displayed through this card
```

If anyone has ideas on how to make such thing clean, he may post it here. So far, I'm thinking of providing a fake hass property to sub-cards which would wrap accesses to state.
